### ISSUE TITLE
Setting versioner.variables.update_available.false to the White Color (§f) with a Lang file will break any CustomMainMenu configuration where a custom Background is used

### ISSUE THREAD

**Issue by Librv** [TCreopargh/Versioner#4]
Hello, it's me again. Found an issue where, as the title says, having the ```versioner.variables.update_available.false``` set to be any text with the ```§f``` minecraft color code (white) will break any CustomMainMenu configuration where a custom background is used, whether it is a single image or a slideshow.

Here is what happens:
![Capture](https://user-images.githubusercontent.com/73041325/126550403-0e8fb223-4e14-499d-9c44-f2783b08e25b.PNG)
![Screenshot (585)](https://user-images.githubusercontent.com/73041325/126550049-080e31ac-7593-4cab-8a6e-0f70af690d45.png)

The interesting thing is that when hovering over the text, the background will appear
![Screenshot (586)](https://user-images.githubusercontent.com/73041325/126550489-2a8652a8-be8f-4388-8b89-0cd120d4c50e.png)

This example CustomMainMenu config uses a single image. When using a slideshow, hovering over the text will only show you the transitions.

Note that this whole minecraft instance only has Versioner, CustomMainMenu and all their required mods. [Modlist](https://i.nuuls.com/nfC3c.png). 
The only change made to the CustomMainMenu auto generated config file is removing the default minecraft panorama and setting a static image.
The only change made to the Versioner auto generated config file is adding a [link to a .json](https://raw.githubusercontent.com/EvergoodTeam/Evergood/main/versioner.json) to verify the version.

Using any other color or no color at all (afaik) doesn't cause this issue.
![Screenshot (587)](https://user-images.githubusercontent.com/73041325/126551660-2c86a003-0c5a-4ab5-a1fb-9d2eedcbb9a9.png)

**Comment by TCreopargh** [comment]
Hmmm that's a very weird issue, try to use §r instead?

**Comment by Librv** [comment]
Works, and for whatever reason now using §f doesn't cause any issue, strange. Closing the issue.
